-- AlterTable
ALTER TABLE "Round"
ADD COLUMN "oddsDown" DECIMAL(6, 3) NOT NULL DEFAULT 1.95,
ADD COLUMN "oddsUp" DECIMAL(6, 3) NOT NULL DEFAULT 1.95;

-- AlterTable
ALTER TABLE "Bet"
ADD COLUMN "odds" DECIMAL(6, 3) NOT NULL DEFAULT 1.95;

